# ======================================================================================================================
# INPUT FILES LOCATION AND SIMPLE TRANSFORMATIONS
# ======================================================================================================================

input_data_dir: data


input_output_file_details:
  file_name: input_output_data.csv

  create_single_columns:
    rho_start: '1 - 1/df.keff_start'
    rho_max: '1 - 1/df.keff_max'

  create_multiple_columns:
      rhoN: '1 - 1/df.keffN'


monocore_file_details:
  file_name: monocores_dictionary.xlsx
  sheet_name: summary

  create_single_columns:
    rho_start: '1 - 1/df.keff_start'
    rho_max: '1 - 1/df.keff_max'


monocore_evolution_file_details:
  file_name: monocores_dictionary.xlsx
  keep_columns:
    - keff
    - ppf

  create_single_columns:
    rho: '1 - 1/df.keff'


# ======================================================================================================================
# MODELING - DATA RELATED
# ======================================================================================================================

use_normalization_layer: False
use_one_hot_encoding: False
use_monocores: False

train_split_ratio: 0.2

# Possible input colum names:
#
# - cycle_length_in_days
# - keff_max
# - pxy_max
# - pz_max
# - keff_start
# - ppf_start
# - ppf_max
# - ppf_end
# - rho_start
# - rho_max
# - keff_evolution
# - rho_evolution
# - ppf_evolution
input_columns:
  - cycle_length_in_days

# Possible output columns names:
#
# - keff_start
# - keff_max
# - ppf_start
# - ppf_max
# - ppf_end
# - cycle_length_in_days
# - rho_start
# - rho_max
#
# - keff_evolution
# - rho_evolution
output_columns:
  - cycle_length_in_days

# ======================================================================================================================
# MODELING - HYPERPARAMETERS
# ======================================================================================================================



# ======================================================================================================================
# OUTPUT FILE PATH
# ======================================================================================================================